name: Publish Crate.io

on:
  workflow_run:
    workflows: ['Bump-Version']
    types: [completed]
    branches:
      - 'main'
      
jobs:
  publish_crate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Publish to Crates.io
        working-directory: rust 
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: cargo publish --verbose
